import {
  Layers,
  Minimize2,
  Maximize2,
  RotateCw,
  Crop,
  Sparkles,
  FileText,
  ScanText,
  FileSpreadsheet,
  Presentation,
  Code,
  FileCheck,
  Search,
  ShieldAlert,
  Hash,
  ListOrdered,
  FileImage,
} from "lucide-react";

export const PDF_TOOLS_CATALOG = [
  // Modification Suite
  {
    id: "merge",
    name: "Merge PDF",
    category: "Modification",
    description: "Combine multiple PDF streams into a unified document in custom order.",
    icon: Layers,
    badge: "Fast Async",
  },
  {
    id: "split",
    name: "Split PDF",
    category: "Modification",
    description: "Extract specific page ranges or burst PDF into individual documents.",
    icon: Maximize2,
    badge: "Ranges Support",
  },
  {
    id: "compress",
    name: "Compress & Optimize",
    category: "Modification",
    description: "Smart raster downsampling, font subsetting, and stream deflation.",
    icon: Minimize2,
    badge: "Up to 80% Smaller",
  },
  {
    id: "rotate",
    name: "Rotate Pages",
    category: "Modification",
    description: "Rotate specific or all pages clockwise by 90°, 180°, or 270°.",
    icon: RotateCw,
    badge: "Zero Loss",
  },
  {
    id: "crop",
    name: "Crop Geometry",
    category: "Modification",
    description: "Trim page margins or select custom rectangular crop regions.",
    icon: Crop,
    badge: "Exact Points",
  },
  {
    id: "watermark",
    name: "Stamp Watermark",
    category: "Modification",
    description: "Add diagonal enterprise confidentiality text or transparent image stamp.",
    icon: Sparkles,
    badge: "Custom Opacity",
  },
  {
    id: "bates",
    name: "Bates Numbering",
    category: "Legal & Audit",
    description: "Sequential legal numbering with custom alphanumeric prefixes and digits.",
    icon: Hash,
    badge: "Legal Standard",
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    category: "Modification",
    description: "Stamp dynamic 'Page N of Total' headers/footers in custom positions.",
    icon: ListOrdered,
    badge: "Dynamic Layout",
  },
  {
    id: "grayscale",
    name: "Convert to Grayscale",
    category: "Optimization",
    description: "Convert color vectors and raster bitmaps to 8-bit DeviceGray channels.",
    icon: FileText,
    badge: "Print Ready",
  },
  {
    id: "flatten",
    name: "Flatten Layers & Forms",
    category: "Modification",
    description: "Merge interactive form fields, annotations, and vector layers into static pages.",
    icon: FileCheck,
    badge: "Secure Bake",
  },
  {
    id: "compare",
    name: "Compare Visual Diff",
    category: "Audit & Analysis",
    description: "Pixel and text differential engine highlighting document revisions.",
    icon: Search,
    badge: "Side-by-Side",
  },
  {
    id: "metadata",
    name: "Metadata Editor",
    category: "Security",
    description: "Inspect, update, or scrub author, producer, title, and creation history.",
    icon: Code,
    badge: "XMP Sanitizer",
  },
  // Conversion Suite
  {
    id: "to-docx",
    name: "PDF to Word (.docx)",
    category: "Conversion",
    description: "High-fidelity conversion preserving headings, paragraphs, and styling.",
    icon: FileText,
    badge: "Editable Word",
  },
  {
    id: "to-excel",
    name: "PDF to Excel (.xlsx)",
    category: "Conversion",
    description: "Extract tabular matrix and financial statements into clean spreadsheets.",
    icon: FileSpreadsheet,
    badge: "Table Detection",
  },
  {
    id: "to-pptx",
    name: "PDF to PowerPoint",
    category: "Conversion",
    description: "Convert slides and document pages into editable presentation decks.",
    icon: Presentation,
    badge: "16:9 Widescreen",
  },
  {
    id: "to-images",
    name: "PDF to Images",
    category: "Conversion",
    description: "Render pages to high-resolution PNG, JPEG, or WebP graphics at custom DPI.",
    icon: FileImage,
    badge: "PNG / JPG / WEBP",
  },
  {
    id: "ocr",
    name: "Dual-Engine OCR",
    category: "AI & OCR",
    description: "Tesseract + PaddleOCR with OpenCV deskewing and searchable PDF generation.",
    icon: ScanText,
    badge: "Searchable PDF",
  },
  {
    id: "deep-redact",
    name: "Deep Redaction Studio",
    category: "Security",
    description: "Physically burn raster pixels and purge font glyphs for SSN, PII, and emails.",
    icon: ShieldAlert,
    badge: "Zero Remnants",
  },
];
